apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv

spec:
  storageClassName: prometheus-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 512Mi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/prometheus-volume/